version: '3.1'

services:
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVsomepasswordmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  botsandserver:
    image: docker.io/library/balance-checker-bot:dev
    container_name: bc-server
    volumes:
      - ./balance_checker_bot/ssl/cert.pem:/src/app/balance_checker_bot/ssl/cert.pem
      - ./balance_checker_bot/ssl/key.pem:/src/app/balance_checker_bot/ssl/key.pem
      - .env:/src/app/.env

    ports:
      - 8000:8000
    #  - "your_host_port:your_container_port"  # Adjust as needed
    depends_on:
      - cache
volumes:
  cache:
    driver: local
